# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list
  install-argocd:
    desc: Deploy ArgoCD using Helmfile
    cmds:
      - helmfile apply -f argocd.yaml
    dir: argo-cd
