apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: default
      hostname: "*.yuchiki.net"
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: yuriacats
      hostname: "*.yuriacats.net"
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: factorio
      hostname: "factorio.yuchiki.net"
      port: 34197
      protocol: UDP
      allowedRoutes:
        namespace:
          from: factorio
