apiVersion: v1
kind: Service
metadata:
  name: home-dns
  namespace: home-dns
spec:
  type: NodePort
  selector:
    app: coredns
  ports:
    - name: dns
      port: 53
      nodePort: 30053
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
      nodePort: 30053
