apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: web3-front-deployment
spec:
  selector:
    matchLabels:
      app: web3-front
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: web3-front
    spec:
      containers:
      - name: web3-front
        image: 561712284442.dkr.ecr.ap-northeast-1.amazonaws.com/web3blog_frontend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: yuria-aws-ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web3front-service
spec:
  type: NodePort
  selector:
    app: web3-front
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30010

