apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: web3-front-deployment
  namespace: blog-yuriacats-net
spec:
  selector:
    matchLabels:
      app: web3-front
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: web3-front
    spec:
      containers:
        - name: web3-front
          image: public.ecr.aws/x6d7c5q4/yuriacatsblog/front:c9d7c920fb7713bd706403b4c24a91fb48144f47
          ports:
            - containerPort: 3000
          env:
            - name: BLOGAPI
              value: "http://web3backend-service:80"

      imagePullSecrets:
        - name: yuria-aws-ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web3front-service
  namespace: blog-yuriacats-net
spec:
  type: ClusterIP
  selector:
    app: web3-front
  ports:
    - port: 3000
      targetPort: 3000
