apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http
  namespace: blog-yuriacats-net
spec:
  parentRefs:
    - name: gateway
      namespace: istio-gateway
      sectionName: default
  hostnames: ["web3blog.yuchiki.net", "blog.yuriacats.net"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: web3front-service
          port: 3000
