apiVersion: v1
kind: Service
metadata:
  name: web3blog-mysql
  namespace: blog-yuriacats-net
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: blog-yuriacats-net
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: sql-init-config
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName:  blog-yuriacats-net-mysql-data-claim
      - name: sql-init-config
        configMap:
            name: db-init-configmap
            items:
              - key: init.sql
                path: init.sql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-configmap
data:
  # init.sqlファイルをしてコンテナ内にマッピングされる。
  init.sql: |
    CREATE DATABASE webblog;
    SET CHARSET UTF8;
    SET character_set_server=UTF8;
    SET character_set_database=UTF8;
    USE webblog;
    CREATE TABLE tag_name(
        id int AUTO_INCREMENT PRIMARY KEY,
        name varchar(20) UNIQUE NOT NULL
        );
    CREATE TABLE post(
        id int AUTO_INCREMENT PRIMARY KEY,
        slug varchar(20) UNIQUE NOT NULL,
        create_date DATETIME DEFAULT CURRENT_TIMESTAMP
        );
    CREATE TABLE tag_post(
            tag_id int NOT NULL, 
            post_id int NOT NULL,
            FOREIGN KEY (tag_id) REFERENCES tag_name(id) ,
            FOREIGN KEY (post_id) REFERENCES post(id)
        );
    CREATE TABLE author(
        id int AUTO_INCREMENT PRIMARY KEY,
        name varchar(20) NOT NULL
        );
    CREATE TABLE author_secret(
        author_id int PRIMARY KEY UNIQUE,
        email varchar(256) UNIQUE NOT NULL,
        password varchar(256) NOT NULL, 
        FOREIGN KEY (author_id) REFERENCES author(id) 
        );
    CREATE TABLE post_revision(
        id int UNIQUE AUTO_INCREMENT PRIMARY KEY,
        create_date DATETIME DEFAULT CURRENT_TIMESTAMP ,
        title varchar(256) NOT NULL,
        author_id int NOT NULL,
        post_id int NOT NULL,
        public int NOT NULL, 
        post_data MEDIUMTEXT NOT NULL,
        FOREIGN KEY (author_id) REFERENCES author(id), 
        FOREIGN KEY (post_id) REFERENCES post(id) 
    );
    SET CHARSET UTF8;
    CREATE USER backend IDENTIFIED WITH mysql_native_password BY 'toor';
    GRANT SELECT, INSERT ON webblog.* TO backend;
