apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-yuriacats-net-mysql-data-claim
  namespace: blog-yuriacats-net
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
