apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-yuriacats-net-mysql-data
spec:
  claimRef:
    namespace: blog-yuriacats-net
    name: blog-yuriacats-net-mysql-data-claim
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/lib/kubernetes-peristent-volume/blog.yuriacats.net/mysql-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: blog.yuriacats.net_persistent-volume_mysql-data
          operator: In
          values:
          - "true"
