apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: istio-ingress
  name: letsencrypt-prod
spec:
  acme:
    email: 14884013+yuchiki@users.noreply.github.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - yurichiki.click
        dns01:
          route53:
            region: ap-northeast-1
            accessKeyIDSecretRef:
              name: aws-credentials
              key: aws-access-key-id
            secretAccessKeySecretRef:
              name: aws-credentials
              key: aws-secret-access-key
