apiVersion: v1
kind: Namespace
metadata:
  name: factorio

---
apiVersion: v1
kind: Service
metadata:
  name: factorio-service
  namespace: factorio
spec:
  type: NodePort
  selector:
    app: factorio
  ports:
    - port: 34197
      targetPort: 34197
      nodePort: 34197
    - port: 27015
      targetPort: 27015
      nodePort: 27015
