apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-volume-claim
  namespace: factorio
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
