apiVersion: v1
kind: Namespace
metadata:
  name: factorio

---
apiVersion: v1
kind: Service
metadata:
  name: factorio-service
  namespace: factorio
spec:
  type: NodePort
  selector:
    app: factorio
  ports:
    - name: factorio
      protocol: UDP
      port: 34197
      targetPort: 34197
      nodePort: 30893
    - name: factorio-rcon
      port: 27015
      targetPort: 27015
      nodePort: 30894
