apiVersion: v1
kind: Service
matadata:
  name: factorio-service
  namespace: factorio
spec:
  selector:
    app: factorio-server
  ports:
    - protocol: UDP
      port: 31497
      targetPort: 31497
