apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-volume-claim
  namespace: factorio
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio-volume
  namespace: factorio
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/lib/kubernetes-persistent-volume/factorio
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: factorio_persistent-volume_factorio
              operator: In
              values:
                - "true"
