apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: istio-system
spec:
  project: default
  source:
    chart: istio/base
    repoURL:  https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22,.1
    helm:
      releaseName: istio-base
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
