apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: growi-set
  namespace: argocd  # or argo-cd-appsets
spec:
  generators:
    - list:
        elements:
          - name: growi
            cluster: in-cluster
            path: growi
          - name: istio-ingress
            cluster: in-cluster
            path: istio
          - name: argo-cd-appsets
            cluster: in-cluster
            path: argo-cd-appsets

  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      source:
        repoURL: https://github.com/yuchiki/test-manifests
        targetRevision: add_argocd_manifest
        path: '{{path}}'
