apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'argo-cd-appsets'
spec:
  destination:
    namespace: argo-cd-appsets
    server: https://kubernetes.default.svc
  source:
    path: argo-cd-appsets
    repoURL: 'https://github.com/yuchiki/test-manifests'
    targetRevision: add_argocd_manifest
  sources: []
  project: default

