apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http
  namespace: growi
spec:
  parentRefs:
    - name: gateway
      namespace: istio-ingress
      sectionName: yuchiki
  hostnames: ["growi.yuchiki.net","growi.yuriacats.net"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: growi
          port: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-internal
  namespace: growi
spec:
  parentRefs:
    - name: gateway
      namespace: istio-ingress
      sectionName: home
  hostnames: ["growi.home"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: growi
          port: 3000
