apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growi-mongo-data-claim
  namespace: growi
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: growi-mongo-data
spec:
  claimRef:
    namespace: growi
    name: growi-mongo-data-claim
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/lib/kubernetes-persistent-volume/growi/mongo-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: growi_persistent-volume_mongo-data
              operator: In
              values:
                - "true"
