apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http
  namespace: home-chat
spec:
  parentRefs:
    - name: gateway
      namespace: istio-ingress
      sectionName: default
    - name: gateway
      namespace: istio-ingress
      sectionName: home
  hostnames: ["yurichikiserver.home", "chat.local.yurichiki.click" ]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: home-chat
          port: 3000
