apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: home-chat-http-route-internal
  namespace: home-chat
spec:
  parentRefs:
    - name: gateway
      namespace: istio-gateway
      sectionName: home
  hostnames: ["yurichikiserver.home" ]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: home-chat
          port: 3000
