apiVersion: v1
kind: Namespace
metadata:
  name: home-chat

---
apiVersion: v1
kind: Service
metadata:
  name: home-chat-service
  namespace: home-chat
spec:
  type: NodePort
  selector:
    app: home-chat
  ports:
    - name: home-chat
      port: 3000
      targetPort: 3000
